services:
  office:
    image: "onlyoffice/documentserver:9.4.0.1"
    restart: unless-stopped
    volumes:
      - ./etc/documentserver/default.json:/etc/onlyoffice/documentserver/default.json
      - ./resources/require.js:/var/www/onlyoffice/documentserver/web-apps/vendor/requirejs/require.js
      - ./resources/common/main/resources/img/header:/var/www/onlyoffice/documentserver/web-apps/apps/common/main/resources/img/header
      - ./resources/documenteditor/main/resources/css/app.css:/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/resources/css/app.css
      - ./resources/documenteditor/mobile/css/526.dfa9fb21284eb383a313.css:/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/mobile/css/526.dfa9fb21284eb383a313.css
      - ./resources/presentationeditor/main/resources/css/app.css:/var/www/onlyoffice/documentserver/web-apps/apps/presentationeditor/main/resources/css/app.css
      - ./resources/presentationeditor/mobile/css/923.37d51add171f0180b4e7.css:/var/www/onlyoffice/documentserver/web-apps/apps/presentationeditor/mobile/css/923.37d51add171f0180b4e7.css
      - ./resources/spreadsheeteditor/main/resources/css/app.css:/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/css/app.css
      - ./resources/spreadsheeteditor/mobile/css/611.3c6090d7986e77474e44.css:/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/mobile/css/611.3c6090d7986e77474e44.css
    environment:
      JWT_SECRET: ${APP_KEY}
